server:
  port: 8000

spring:
  cloud:
    # 注册服务
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    gateway:
      discovery:
        locator:
          enabled: true  # 自动根据 Nacos 服务名创建路由（如 /nova-user/**）
      routes:
        - id: nova-user-route
          uri: lb://nova-user
          predicates:
            - Path=/user/**
        - id: nova-product-route
          uri: lb://nova-product
          predicates:
            - Path=/product/**